### ISSUE TITLE
IDistributedCache 和 RedisHelper 不能同时使用吗？

### ISSUE THREAD

**Issue by 54Ezreal** [2881099/Microsoft.Extensions.Caching.CSRedis#3]
如果我用IDistributedCache.SetObject("key","123") 设置缓存，用RedisHelper.Get("key") 就会出错：
"WRONGTYPE Operation against a key holding the wrong kind of value"

**Comment by 2881099** [comment]
是的，IDistributedCache 存的都是hash 类型，微软那个库也是这样。

RedisHelper.Get 是获取string，所以类型错误了。你可以试试，RedisHelper.HGet，看看返回的内容。

**Comment by 54Ezreal** [comment]
@2881099  3Q ，明白了。
